version: '3.7'

services:
  nudges:
    build: .
    volumes:
      - .:/usr/src/personalised_nudges
    ports:
      - 80:80
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    expose: 
      - 5432

volumes:
  postgres_data: